# Site settings
title: 張軒瑞 | Github
description: 
username: Zhang Xuanrui
user_description: 
user_title: Algorithm Engineer
email: zxryhjp@yahoo.co.jp

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
