# Site settings
title: 張軒瑞 | Zhang Xuanrui
description: 
username: Zhang Xuanrui
user_description: I'm an Algorithm Engineer, major in the field of CV, NLP and OCR.
Always searching for the next challenge; no task is too scary nor too difficult.
user_title: Algorithm Engineer
email: zxryhjp@yahoo.co.jp

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
